version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

     
  build:
    commands:
      - echo Maven Build ...
      - mvn clean package

       
artifacts:
     files:
      - target/spring-boot.jar
      - imagedefinitions.json
